version: '3'
services:
  app:
    image: circleci/php
    tty: true
    working_dir: /srv
    volumes:
      - .:/srv/
    environment:
      - "ELASTICSEARCH_HOST=elasticsearch"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.4
    links:
      - elasticsearch
    ports:
      - 5601:5601
  logstash:
    image: docker.elastic.co/logstash/logstash:6.5.4
    links:
      - elasticsearch
