version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    ports:
      - 9200:9200
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.4
    links:
      - elasticsearch:elasticsearch
    ports:
      - 5601:5601
  logstash:
    image: docker.elastic.co/logstash/logstash:6.5.4
    links:
      - elasticsearch:elasticsearch
