version: 2
jobs:
  build:
    docker:
      - image: circleci/php
        environment:
          - "ELASTICSEARCH_HOST=localhost"
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
        environment:
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          - v1-dependencies-

      - run: make

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run: dockerize -wait tcp://localhost:9200 -timeout 1m

      - run: make elasticsearch
      - run: make test
